# Generated by Django 3.0 on 2020-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('num', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'energy_coal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyElectric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'energy_electric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FixedInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('num', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixed_invest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gdp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('num', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_invest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbFixedInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nb_fixed_invest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NbHouseInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nb_house_invest',
                'managed': False,
            },
        ),
    ]
